---
method: opensearch
log_level: INFO
auto_continue: true
ssh_config:
  username: root
  password: "root"
  sudo_pass: ""
  sudo: false
  timeout: 10
  ssh_config_file: demo/docker/ssh_config
  host_config:
    log_files:
      - /var/log/mail.log
    log_parser: NoSpaceInDatetimeParser
    time_format: "%Y-%m-%dT%H:%M:%S"
opensearch_config:
  host: "localhost"
  port: 9200
  username: "admin"
  password: "wg328GY@3HUY76"
  index: "mailtrace-logs"
  use_ssl: true
  verify_certs: false
  time_zone: "+08:00"
  timeout: 10
  mapping:
    facility: "log.syslog.facility.name"
    hostname: "host"
    message: "message"
    timestamp: "timestamp"
    service: "appname"
